const COUNTRY_CODES = [
  'BR', 'PT', 'AO', 'MZ',
  'AF', 'AL', 'DZ', 'AD', 'AG', 'AR', 'AM', 'AU', 'AT', 'AZ',
  'BS', 'BH', 'BD', 'BB', 'BY', 'BE', 'BZ', 'BJ', 'BT', 'BO', 'BA', 'BW', 'BN', 'BG', 'BF', 'BI',
  'CV', 'KH', 'CM', 'CA', 'CF', 'TD', 'CL', 'CN', 'CO', 'KM', 'CG', 'CR', 'HR', 'CU', 'CY', 'CZ',
  'DK', 'DJ', 'DO',
  'EC', 'EG', 'SV', 'GQ', 'ER', 'EE', 'SZ', 'ET',
  'FJ', 'FI', 'FR',
  'GA', 'GM', 'GE', 'DE', 'GH', 'GR', 'GT', 'GN', 'GW', 'GY',
  'HT', 'HN', 'HU',
  'IS', 'IN', 'ID', 'IR', 'IQ', 'IE', 'IL', 'IT',
  'JM', 'JP', 'JO',
  'KZ', 'KE', 'KW', 'KG',
  'LA', 'LV', 'LB', 'LS', 'LR', 'LY', 'LI', 'LT', 'LU',
  'MG', 'MW', 'MY', 'MV', 'ML', 'MT', 'MR', 'MU', 'MX', 'MD', 'MC', 'MN', 'ME', 'MA', 'MM',
  'NA', 'NP', 'NL', 'NZ', 'NI', 'NE', 'NG', 'NO',
  'OM',
  'PK', 'PA', 'PG', 'PY', 'PE', 'PH', 'PL',
  'QA',
  'RO', 'RU', 'RW',
  'SA', 'SN', 'RS', 'SL', 'SG', 'SK', 'SI', 'SO', 'ZA', 'SS', 'ES', 'LK', 'SD', 'SR', 'SE', 'CH', 'SY',
  'TW', 'TJ', 'TZ', 'TH', 'TL', 'TG', 'TT', 'TN', 'TR', 'TM',
  'UG', 'UA', 'AE', 'GB', 'US', 'UY', 'UZ',
  'VE', 'VN',
  'YE',
  'ZM', 'ZW',
];

export const getCountries = (t) =>
  COUNTRY_CODES.map(code => ({ code, name: t(`countries.${code}`) }));
